"""Nullain Agent SDK — AgentLoop ReAct Core Execution Loop."""

import time
import uuid

from nullain.errors import BudgetExceededError, NullainError
from nullain.events import (
    BaseEvent,
    Conversation,
    ErrorEvent,
    EventBus,
    EventStore,
    ModelResponseEvent,
    ToolCallEvent,
    ToolResultEvent,
    UserMessageEvent,
)
from nullain.llm import CompletionChunk, CompletionRequest, LLMProvider
from nullain.tools import ToolRegistry


class AgentLoop:
    """ReAct Execution Loop for Nullain Agent."""

    def __init__(
        self,
        provider: LLMProvider,
        tools: ToolRegistry,
        event_bus: EventBus | None = None,
        event_store: EventStore | None = None,
        model: str = "qwen3-coder:480b-cloud",
        max_steps: int = 25,
        max_tokens: int | None = 100_000,
        timeout: float = 300.0,
    ) -> None:
        self.provider = provider
        self.tools = tools
        self.event_bus = event_bus or EventBus()
        self.event_store = event_store
        self.model = model
        self.max_steps = max_steps
        self.max_tokens = max_tokens
        self.timeout = timeout

    async def _emit(self, event: BaseEvent) -> None:
        """Emit event to bus and persist to store if configured."""
        await self.event_bus.publish(event)
        if self.event_store is not None:
            await self.event_store.append(event)

    async def run(
        self,
        prompt: str,
        session_id: str | None = None,
        events_history: list[BaseEvent] | None = None,
    ) -> str:
        """Run the ReAct agent loop for a user prompt.

        Returns:
            The final text response generated by the agent.
        """
        sess_id = session_id or str(uuid.uuid4())
        start_time = time.time()
        accumulated_events: list[BaseEvent] = list(events_history or [])

        # Emit initial UserMessageEvent
        user_ev = UserMessageEvent(session_id=sess_id, content=prompt)
        await self._emit(user_ev)
        accumulated_events.append(user_ev)

        step = 0
        total_tokens = 0
        final_text = ""

        while step < self.max_steps:
            # Termination Check: Timeout
            if (time.time() - start_time) > self.timeout:
                err_ev = ErrorEvent(
                    session_id=sess_id,
                    error_type="TimeoutError",
                    message=f"Agent loop timed out after {self.timeout} seconds",
                )
                await self._emit(err_ev)
                raise NullainError(f"Agent loop timed out after {self.timeout} seconds")

            # Termination Check: Token Budget
            if self.max_tokens is not None and total_tokens >= self.max_tokens:
                err_ev = ErrorEvent(
                    session_id=sess_id,
                    error_type="BudgetExceededError",
                    message=f"Token budget of {self.max_tokens} exceeded",
                )
                await self._emit(err_ev)
                raise BudgetExceededError(f"Token budget of {self.max_tokens} exceeded")

            step += 1
            state = Conversation.fold(sess_id, accumulated_events)
            tool_specs = self.tools.list_specs()

            req = CompletionRequest(
                model=self.model,
                messages=state.messages,
                tools=tool_specs if tool_specs else None,
                stream=False,
            )

            response_chunk: CompletionChunk = await self.provider.generate(req)

            if response_chunk.usage:
                total_tokens += response_chunk.usage.total_tokens

            model_ev = ModelResponseEvent(
                session_id=sess_id,
                model=self.model,
                content=response_chunk.delta_text,
                tool_calls=tuple(response_chunk.tool_calls) if response_chunk.tool_calls else None,
                usage=response_chunk.usage,
            )
            await self._emit(model_ev)
            accumulated_events.append(model_ev)

            # If no tool calls, completion is reached
            if not response_chunk.tool_calls:
                final_text = response_chunk.delta_text or ""
                break

            # Execute tool calls
            for tc in response_chunk.tool_calls:
                tc_ev = ToolCallEvent(
                    session_id=sess_id,
                    call_id=tc.id,
                    tool_name=tc.name,
                    arguments=tc.arguments,
                )
                await self._emit(tc_ev)
                accumulated_events.append(tc_ev)

                try:
                    res_output = await self.tools.execute(tc.name, tc.arguments)
                    is_err = False
                except Exception as err:
                    res_output = f"Tool Execution Error: {err}"
                    is_err = True

                res_ev = ToolResultEvent(
                    session_id=sess_id,
                    call_id=tc.id,
                    tool_name=tc.name,
                    output=res_output,
                    is_error=is_err,
                )
                await self._emit(res_ev)
                accumulated_events.append(res_ev)

        if step >= self.max_steps:
            err_ev = ErrorEvent(
                session_id=sess_id,
                error_type="MaxStepsExceeded",
                message=f"Agent loop reached maximum step count ({self.max_steps})",
            )
            await self._emit(err_ev)

        return final_text


__all__ = ["AgentLoop"]
